In [1]:
import pandas as pd
import numpy as np

In [2]:
# How likely is it that you roll doubles when rolling two dice?

outcomes = [1,2,3,4,5,6]
n_sim = 100000
n_trials = 2

rolls = np.random.choice(outcomes, (n_sim, n_trials))

In [3]:
rolls = pd.DataFrame(rolls)
rolls

0  1
0      3  4
1      3  6
2      4  2
3      6  5
4      5  4
...   .. ..
99995  4  1
99996  2  5
99997  5  1
99998  1  5
99999  6  6

[100000 rows x 2 columns]

In [4]:
double = (rolls[0] == rolls[1])
double

0        False
1        False
2        False
3        False
4        False
         ...  
99995    False
99996    False
99997    False
99998    False
99999     True
Length: 100000, dtype: bool

In [5]:
double.mean()

0.16764

In [6]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? 

outcomes = ['Heads', 'Tails']
n_sim = 100000
n_trials = 8

flips = np.random.choice(outcomes, (n_sim, n_trials))
flips

array([['Tails', 'Tails', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Tails', 'Heads', ..., 'Heads', 'Tails', 'Heads'],
       ['Heads', 'Tails', 'Tails', ..., 'Tails', 'Tails', 'Tails'],
       ...,
       ['Tails', 'Heads', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Tails', 'Heads', ..., 'Heads', 'Heads', 'Tails'],
       ['Tails', 'Heads', 'Tails', ..., 'Tails', 'Tails', 'Heads']],
      dtype='<U5')

In [7]:
h_flip = (flips == 'Heads')
h_flip

array([[False, False,  True, ...,  True,  True, False],
       [False, False,  True, ...,  True, False,  True],
       [ True, False, False, ..., False, False, False],
       ...,
       [False,  True,  True, ...,  True,  True, False],
       [False, False,  True, ...,  True,  True, False],
       [False,  True, False, ..., False, False,  True]])

In [8]:
sum_heads = h_flip.sum(axis=1)

wins = (sum_heads == 3)
wins

array([ True,  True, False, ..., False, False, False])

In [9]:
win_rate = wins.mean()
win_rate

0.21859

In [10]:
# What is the probability of getting more than 3 heads?

In [12]:
wins = (sum_heads > 3)
wins.mean()

0.63717

In [47]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. 
# Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that 
# the two billboards I drive past both have data science students on them?

ds = .25
nbill = ncols = 2
n_sim = nrows = 100000
data = np.random.random((nrows, ncols))
data


array([[0.80869253, 0.74680034],
       [0.55693629, 0.80066271],
       [0.89807697, 0.638893  ],
       ...,
       [0.83009959, 0.6832739 ],
       [0.34216238, 0.50167274],
       [0.71964391, 0.73392773]])

In [50]:
ds_bill = (data < ds)
ds_bill

array([[False, False],
       [False, False],
       [False, False],
       ...,
       [False, False],
       [False, False],
       [False, False]])

In [51]:
(ds_bill.sum(axis=1) == 2).mean()

0.06289

In [13]:
# Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from 
# the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how 
# likely is it that I will be able to buy some poptarts on Friday afternoon? 
# (Remember, if you have mean and standard deviation, use the np.random.normal) 
# You'll need to make a judgement call on how to handle some of your values

pop_per_day = np.random.normal(3, 1.5, size=100000)
pop_per_day

array([6.67176746, 2.04059647, 3.10675758, ..., 2.52127094, 1.53086843,
       2.33079964])

In [14]:
pop_per_day = pop_per_day.reshape(20000,5)
pop_per_day.sum(axis=1)

array([24.40234023, 18.84766974, 19.87539095, ..., 11.98374923,
       14.57139445, 13.53464288])

In [15]:
pops_sold = pop_per_day.sum(axis=1) <= 16 # accounting for an entire poptart available for purchase
pops_sold

array([False, False, False, ...,  True,  True,  True])

In [16]:
pops_sold.mean()

0.6219

In [66]:
# Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

men_avg_ht = np.random.normal(178, 8, size=10000)
wmn_avg_ht = np.random.normal(170, 6, size=10000)

In [67]:
men_avg_ht

array([183.58339287, 170.62379607, 177.37017288, ..., 166.00287164,
       179.62134517, 177.37257385])

In [68]:
wmn_avg_ht

array([165.76589611, 168.11168061, 168.3835817 , ..., 164.6603754 ,
       168.71227777, 168.25078127])

In [87]:
woman_is_taller = (men_avg_ht < wmn_avg_ht)
woman_is_taller.mean()

0.2128

In [135]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted 
# and the installation fails. What are the odds that after having 50 students download anaconda, no one has an 
# installation issue? 100 students?

corrupt_dl = 0.004
n_sim = np.random.random((100000, 50))
no_corrupts = (n_sim > corrupt_dl).sum(axis=1) == 50
no_corrupts.mean()

0.81694

In [137]:
corrupt_dl = 0.004
n_sim = np.random.random((100000, 100))
no_corrupts = (n_sim > corrupt_dl).sum(axis=1) == 100
no_corrupts.mean()

0.66914

In [138]:
# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

corrupt_dl = 0.004
n_sim = np.random.random((100000, 150))
corrupts = (n_sim < corrupt_dl).sum(axis=1)
corrupts.mean()

0.60063

In [139]:
# How likely is it that 450 students all download anaconda without an issue?

corrupt_dl = 0.004
n_sim = np.random.random((100000, 450))
no_corrupts = (n_sim > corrupt_dl).sum(axis=1) == 450
no_corrupts.mean()

0.16385

In [160]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park. 
# However, you haven't seen a food truck there in 3 days. How unlikely is this?

food_truck = .7
n_sim = np.random.random((100000, 3))
n_sim

array([[0.14842807, 0.32548358, 0.00242114],
       [0.28076078, 0.69050737, 0.49050418],
       [0.41904861, 0.59664882, 0.15458394],
       ...,
       [0.29099845, 0.62313578, 0.52363168],
       [0.81824905, 0.88278174, 0.8290073 ],
       [0.63775238, 0.47867045, 0.31291125]])

In [163]:
no_truck = (n_sim > food_truck)
no_truck

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       ...,
       [False, False, False],
       [ True,  True,  True],
       [False, False, False]])

In [166]:
truck_sum = (no_truck.sum(axis=1) == 3)
truck_sum.mean()

0.02654

In [231]:
# How likely is it that a food truck will show up sometime this week?

food_truck = .7
n_sim = np.random.random((100000, 7))
truck = (n_sim < food_truck)
twk = truck.sum(axis=1) > 1
twk.mean()

0.9964

In [170]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? 

people = 23
outcomes = np.arange(1,366)

n_sim = np.random.choice(outcomes, (10000, 23))

In [171]:
n_sim = pd.DataFrame(n_sim)
n_sim

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0     148  252   88  341  206  231  334  147  144  158  ...  313  342  209   
1      73  212  254  174  236   55  175  139  322    7  ...  264  339  216   
2      97  340   75  235  285   41  252  275   55  270  ...  289   24  174   
3     344  332  200  127  292  135  213  234  100  281  ...  225   83   92   
4     135   37  327  218  185  271  241  108   86  322  ...   71  126   98   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   83   15  215   25  223   92  311   45   77   77  ...   19  186  273   
9996   19  150   22   65  269   65  326   56  277  225  ...  175   35  143   
9997  132   32   10    4  245  247  302  205  307    8  ...  253   39  260   
9998   39  221  351   13  319  110  241  186  236  121  ...  259   21  268   
9999  242    6  238  123  290  337  196  216  230  302  ...  261  356  232   

       16   17   18   19   20   21   22  
0     339   27  252  196  354  249  243  
1     227  319   99  343  176  104   58  
2     169  340  128    7  198  299  276  
3     140  281  108  231  358  325  123  
4     285  212  175  217   32  360  232  
...   ...  ...  ...  ...  ...  ...  ...  
9995    1  235  154  339   14  207   20  
9996  305  129  153  103  205   36  139  
9997   10  288   42   59  316  315  160  
9998  342   16   22  190  129  249   69  
9999  163   89   34  102   17  276  203  

[10000 rows x 23 columns]

In [209]:
n_unique = n_sim.nunique(axis=1)
n_unique

0       22
1       23
2       22
3       22
4       23
        ..
9995    22
9996    21
9997    22
9998    23
9999    23
Length: 10000, dtype: int64

In [214]:
shared_bday = (n_unique != 23)
shared_bday.mean()

0.4989

In [220]:
# What if it's 20 people?

outcomes = np.arange(1,366)

n_sim = np.random.choice(outcomes, (10000, 20))


In [221]:
n_sim = pd.DataFrame(n_sim)
n_unique = n_sim.nunique(axis=1)


In [222]:
shared_bday = (n_unique != 20)
shared_bday.mean()

0.4154

In [215]:
# What if it's 40 people?

outcomes = np.arange(1,366)

n_sim = np.random.choice(outcomes, (10000, 40))


In [218]:
n_sim = pd.DataFrame(n_sim)
n_unique = n_sim.nunique(axis=1)


In [219]:
shared_bday = (n_unique != 40)
shared_bday.mean()

0.8902